### ISSUE TITLE
Incompatibility with Nextflow 25.04

### ISSUE THREAD

**Issue by cakirb** [cellgeni/nf-irods-to-fastq#7]
It seems like this part of the pipeline is incompatible with the latest version of Nextflow (25.04), since it seems working well with the version before that (24.10):
```
ERROR ~ Script compilation error
- file : /nfs/users/nfs_c/cellgeni-su/.nextflow/assets/cellgeni/nf-irods-to-fastq/main.nf
- cause: The `publish` section is only allowed in the entry workflow @ line 120, column 9.
           combined_fastq >> "."
           ^

1 error


 -- Check '.nextflow.log' file for details
```

**Comment by prete** [comment]
Indeed, breaking changes in 25.05 [Workflow outputs (third preview)](https://www.nextflow.io/docs/latest/migrations/25-04.html). My guess is that something like this should work:


```diff
@@ -116,9 +116,6 @@ workflow DOWNLOADCRAMS {
         metadata = updateMetadata(json_ch)
     emit:
         combined_fastq
-    publish:
-        combined_fastq >> "."
-
         
 }
 
@@ -155,13 +152,16 @@ workflow {
         // load existing metadata file
         cram_metadata = Channel.fromPath(params.meta, checkIfExists: true).splitCsv( header: true , sep: '\t')
     } 
+
+    fastq_files = []
+
     // Run downloadcrams workflow
     if (params.cram2fastq) {
         DOWNLOADCRAMS(cram_metadata)
         fastq_ch = DOWNLOADCRAMS.out.map {fastq_path, meta -> [meta['sample'], fastq_path]}
                                     .transpose()
                                     .groupTuple()
+        fastq_files = DOWNLOADCRAMS.out.combined_fastq
     // Get fastq files from input
     } else if (params.fastqfiles != null) {
         fastq_ch = Channel.fromPath("${params.fastqfiles}/*.fastq.gz")
@@ -172,11 +172,17 @@ workflow {
     if (params.toftp) {
         UPLOADTOFTP(fastq_ch)
     }
+
+    publish:
+        fastqs = fastq_files
 }
 
 /////////////////////// WORKFLOW OUTPUT DEFINITION ///////////////////////////////////////////////
 // It look stupid (and it is really stupid), but it is the way it work in current nextflow versions
 
 output {
+    fastqs {
+        path '.'
+    }
+}
```

**Comment by Claptar** [comment]
Fixed. See `dev` branch
